---
vsphere_server: "vc01.h2o-2-7752.h2o.vmware.com"
vsphere_username: "administrator@vsphere.local"
vsphere_password: "6-SX1x6yG&tKJHxsgNt"
tkg_user: "tkg-admin"
# Note that the password must conform to the vSphere user password policy.
tkg_user_password: "6-SX1x6yG&tKJHxsgNt"
tkg_role: TKG
cluster_name: vc01cl01
cluster_plan: dev
vsphere_namespace: tkgns1
supervisor_cluster: "vc01cl01-wcp.h2o-2-7752.h2o.vmware.com"
workload_cluster: workload3
vsphere_datacenter: vc01
storage_class: vc01cl01-t0compute
datastore: vsanDatastore
#datastores: [vsanDatastore]
resource_pool: tkg-management-components
#resource_pools: [tkg-management-components]
vm_folder: tkg-management-components
#vm_folders: [tkg-management-components] 
network: "Avi Internal"
#networks: ["Avi Internal"]
distributed_switche: vc01-dvs
#distributed_switches: [vc01-dvs]
distributed_port_group: user-workload
#distributed_port_groups: [user-workload]
needed_privileges_file: needed_privileges.yaml
# TKG 1.6
image_template: photon-3-kube-v1.23.10+vmware.1
#image_templates: [photon-3-kube-v1.23.10+vmware.1]
# TKG 5.1 
#image_templates: [photon-3-kube-v1.22.9+vmware.1]
tanzu_config_template: tanzu_cluster_template.yaml
tanzu_mc_config_filename: tanzu_mgmt_cluster.yaml
certificate_email: "me@vmware.com"

# Complete these in order to complete the tanzu build template yaml...
avi_ca_data_b64: 
avi_cloud_name: 
avi_control_plane_ha_provider: "true"
avi_controller: 
avi_data_network: 
avi_data_network_cidr: 
avi_enable: "true"
avi_labels: ""
avi_management_cluster_vip_network_name: 
avi_management_cluster_vip_network_cidr: 
avi_username: "avi-admin"
avi_password: "6-SX1x6yG&tKJHxsgNt"
avi_service_engine_group: 
cluster_cidr: 100.96.0.0/11
service_cidr: 100.64.0.0/13
enable_audit_logging: "true"
enable_ceip_participation: "true"
enable_mhc: "true"
mhc_unknown_status_timeout: 5m
mhc_false_status_timeout: 12m
identity_management_type: vsphere
infrastructure_provider: vsphere
ldap_bind_dn: 
ldap_bind_password: 
ldap_group_search_base_dn: 
ldap_group_search_filter: 
ldap_group_search_user_attribute: DN
ldap_group_search_group_attribute: 
ldap_group_search_name_attribute: CN
ldap_host: 
ldap_root_ca_data_b64: 
ldap_user_search_base_dn: 
ldap_user_search_filter: 
ldap_user_search_name_attribute: 
ldap_user_search_username: userPrincipalName

oidc_identity_provider_client_id: 
oidc_identity_provider_client_secret: 
oidc_identity_provider_groups_claim: 
oidc_identity_provider_issuer_url: 
oidc_identity_provider_scopes: "email,profile,groups"
oidc_identity_provider_username_claim: email
oidc_identity_provider_name: 

os_arch: amd64
os_name: ubuntu
os_version: "20.04"

tkg_http_proxy_enabled: "false"
tkg_ip_family: ipv4

vsphere_control_plane_disk_gib: "40"
vsphere_control_plane_endpoint: 
vsphere_control_plane_mem_mib: "16384"
vsphere_control_plane_num_cpus: "4"
vsphere_insecure: "true"
vsphere_worker_disk_gib: "40"
vsphere_worker_mem_mib: "4096"
vsphere_worker_num_cpus: "2"
vip_network_interface: "eth0"

# The following two lines are generated by the 'prepare-vsphere.py' script and can be 
# left commented-out
# ssh_public_key:
# vsphere_tls_thumbprint

tanzu_package_registry: "projects.registry.vmware.com/tkg/packages/standard/repo"
tanzu_package_registry_version: "v1.6.1"
tanzu_standard_package_repo_name: "tanzupackages"
installed_packages_namespace: "tanzu-packages"

# Define the additional variables for the Tanzu Kubernetes Cluster creation template
#cp_vmclass_size = "<controlplane_vmclass_type>"
#control_plane_count = "<control_plane_count>"
#worker_node_count = "<worker_node_count>"
#worker_vmclass_size = "<workernode_vmclass_type>"
#ctrd_disksize = "<containerd_volumesize>"
#kubelet_disksize = "<kubelet_volumesize>"
#tkr = "<tanzu_k8s_releaseversion>"

cp_vmclass_size: "best-effort-medium"
control_plane_count: "1"
worker_node_count: "3"
worker_vmclass_size: "best-effort-medium"
ctrd_disksize: "25Gi"
kubelet_disksize: "15Gi"
tkr: "v1.22.9---vmware.1-tkg.1.cc71bc8"
